remote_theme: pages-themes/minimal@v0.2.0
title: Jamie Read
description: DevOps Engineer and Open Source author
author: Jamie Read
logo: /assets/profile.jpg
socials:
  linkedin: https://www.linkedin.com/in/jamieread/
  dev: https://dev.to/jamoyjamie
plugins:
  - jekyll-sitemap
